### ISSUE TITLE
Investigate docusaurus' magic box of routing so links don't break

### ISSUE THREAD

**Issue by kcullion** [icgc-argo/argo-docs#258]
https://drive.google.com/file/d/12a2EcMRPLtcOrjogjCPVXWxkGE77_wfF/view

Problem as seen in video
- on netlify site sometimes a / gets appended at the end which treats the docs page as a folder and breaks the relative links
- this happens on QA too (not just netlify)

**Comment by kcullion** [comment]
note: for launch, I am going to update all the links to the absolute path and see if that fixes this for now

**Comment by ciaranschutte** [comment]
@kcullion you are correct. trailing slash is breaking links. Netlify adds it with it's Pretty URL setting.

**Comment by ciaranschutte** [comment]
https://github.com/facebook/docusaurus/issues/2394

**Comment by kcullion** [comment]
not so pretty netlify...not so pretty. 
I saw it happening on qa too, so to be safe I did the update to all urls on the docs site.

**Comment by ciaranschutte** [comment]
https://v2.docusaurus.io/docs/deployment#deploying-to-netlify
@kcullion should be fixed now. I changed the netlify setting

**Comment by kcullion** [comment]
@ciaranschutte when I go to a netlify link that I had in my browser history, this slash doesn't seem to get added.
Is the QA site also something that will update when new settings get merged? As I still see it happening on pages like https://docs.qa.argo.cancercollaboratory.org/docs/submission-overview

**Comment by kcullion** [comment]
@rosibaj I feel like we can merge this :)

**Comment by rosibaj** [comment]
moved to awaiting release!
